export const DIARY_TEXTS = {
  titleHi: "मेरी पावन साधना गैलरी",
  titleEn: "My Sadhana Diary",
  subtitleHi: "आपके द्वारा पूर्व में सहेजे गए दैनिक पोस्टर",
  subtitleEn: "Revisit your personalized posters saved on this device",
  tabSavedHi: "सहेजे गए",
  tabSavedEn: "Saved",
  tabLikedHi: "पसंदीदा",
  tabLikedEn: "Liked",
  emptySavedHi: "अभी तक कोई पोस्टर संग्रहित नहीं है।",
  emptySavedEn: "Your saved posters diary is empty.",
  btnCreatePosterHi: "पोस्टर बनाएं",
  btnCreatePosterEn: "Create Poster Now",
  emptyLikedHi: "पसंदीदा सूची अभी खाली है।\nपोस्टर या वॉलपेपर को ❤️ आइकन दबाकर पसंदीदा बनाएं।",
  emptyLikedEn: "Your liked list is empty. Mark posters or wallpapers with ❤️ to see them here.",
  btnExplorePostersHi: "पोस्टर गैलरी देखें",
  btnExplorePostersEn: "Explore Posters",
  likedPostersTitleHi: "पसंदीदा पोस्टर",
  likedPostersTitleEn: "Liked Posters",
  likedWallpapersTitleHi: "पसंदीदा वॉलपेपर",
  likedWallpapersTitleEn: "Liked Wallpapers",
  likedLiveWallpapersTitleHi: "पसंदीदा सजीव वॉलपेपर",
  likedLiveWallpapersTitleEn: "Liked Live Wallpapers",
  customizeHi: "बनाएं",
  customizeEn: "Customize",
  proBadge: "👑 Pro",
  freeBadge: "Free",
};
