import {
  Bell,
  BookOpen,
  Download,
  FileText,
  Globe,
  Headphones,
  Heart,
  History,
  Home,
  Image,
  Info,
  Layers,
  Mail,
  MessageSquare,
  Music,
  Palette,
  PlaySquare,
  Shield,
  Sparkles,
  Scroll,
  Star,
  Trophy,
  Upload,
  User,
  Users,
} from 'lucide-react';
import type { NavigationItem, LanguageOption, AboutItem, SettingsItem } from '@/types/navigation';
import { ROUTES } from '@/config/routes';
import { OmIcon } from '@/config/icons';


export const MAIN_NAV_ITEMS: NavigationItem[] = [
  {
    id: 'home',
    titleKey: 'home',
    titleFallback: 'Home',
    route: ROUTES.HOME,
    icon: Home,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'bhajans',
    titleKey: 'browse',
    titleFallback: 'Bhajans',
    route: ROUTES.BHAJANS,
    icon: Music,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'chalisa',
    titleKey: 'chalisa',
    titleFallback: 'Chalisa & Aarti',
    route: ROUTES.CHALISA,
    icon: BookOpen,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'katha',
    titleKey: 'katha',
    titleFallback: 'Katha & Leela',
    route: ROUTES.KATHA,
    icon: Scroll,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'mantras',
    titleKey: 'mantras',
    titleFallback: 'Mantras',
    route: ROUTES.MANTRAS,
    icon: OmIcon,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'audio',
    titleKey: 'audioPlayer',
    titleFallback: 'Audio Bhajans',
    route: ROUTES.AUDIO,
    icon: Headphones,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'shorts',
    titleKey: 'shorts',
    titleFallback: 'Bhakti Shorts',
    route: ROUTES.SHORTS,
    icon: PlaySquare,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'wallpaper',
    titleKey: 'wallpaper',
    titleFallback: 'Wallpapers',
    route: ROUTES.WALLPAPER,
    icon: Image,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'posters',
    titleKey: 'posterMaker',
    titleFallback: 'Blessing Posters',
    route: ROUTES.POSTERS,
    icon: Palette,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'community',
    titleKey: 'community',
    titleFallback: 'Community',
    route: ROUTES.COMMUNITY,
    icon: Users,
    group: 'main',
    permission: 'public',
    visible: true,
  },
  {
    id: 'kirtanAi',
    titleKey: 'kirtanAi',
    titleFallback: 'Narad AI',
    route: ROUTES.NARAD_AI,
    icon: Sparkles,
    group: 'main',
    badge: 'new',
    permission: 'public',
    visible: true,
  },
];

/** Personal section items */
export const PERSONAL_NAV_ITEMS: NavigationItem[] = [
  {
    id: 'favorites',
    titleKey: 'favorites',
    titleFallback: 'Favorites',
    route: ROUTES.LIKED,
    icon: Heart,
    group: 'personal',
    permission: 'auth',
    visible: true,
  },
  {
    id: 'recent',
    titleKey: 'recent',
    titleFallback: 'Recently Played',
    route: ROUTES.HISTORY,
    icon: History,
    group: 'personal',
    permission: 'public',
    visible: true,
  },
  {
    id: 'downloads',
    titleKey: 'downloads',
    titleFallback: 'Downloads',
    route: ROUTES.DOWNLOADS,
    icon: Download,
    group: 'personal',
    permission: 'auth',
    visible: true,
  },
  {
    id: 'leaderboard',
    titleKey: 'leaderboard',
    titleFallback: 'Leaderboard',
    route: ROUTES.LEADERBOARD,
    icon: Trophy,
    group: 'personal',
    permission: 'auth',
    visible: true,
  },
  {
    id: 'notifications',
    titleKey: 'notifications',
    titleFallback: 'Notifications',
    route: ROUTES.NOTIFICATIONS,
    icon: Bell,
    group: 'personal',
    badge: 'notification',
    permission: 'auth',
    visible: true,
  },
];

/** Settings items */
export const SETTINGS_ITEMS: SettingsItem[] = [
  {
    id: 'account',
    titleKey: 'openAccount',
    titleFallback: 'Account',
    route: ROUTES.ACCOUNT,
    icon: User,
  },
  {
    id: 'theme',
    titleKey: 'appearance',
    titleFallback: 'Appearance',
    icon: Layers,
    action: 'theme',
  },
  {
    id: 'storage',
    titleKey: 'storage',
    titleFallback: 'Storage & Downloads',
    route: ROUTES.DOWNLOADS,
    icon: Download,
  },
  {
    id: 'notificationSettings',
    titleKey: 'notifications',
    titleFallback: 'Notifications',
    route: ROUTES.NOTIFICATIONS,
    icon: Bell,
  },
  {
    id: 'accessibility',
    titleKey: 'accessibility',
    titleFallback: 'Accessibility',
    route: ROUTES.ACCOUNT,
    icon: Globe,
  },
  {
    id: 'privacy',
    titleKey: 'privacyPolicy',
    titleFallback: 'Privacy',
    route: ROUTES.PRIVACY,
    icon: Shield,
  },
  {
    id: 'upload',
    titleKey: 'upload',
    titleFallback: 'Upload Bhajan',
    route: ROUTES.UPLOAD,
    icon: Upload,
  },
];

/** About items */
export const ABOUT_ITEMS: AboutItem[] = [
  {
    id: 'about',
    titleKey: 'about',
    titleFallback: 'About Raghavam',
    route: ROUTES.ABOUT,
    icon: Info,
  },
  {
    id: 'privacy',
    titleKey: 'privacyPolicy',
    titleFallback: 'Privacy Policy',
    route: ROUTES.PRIVACY,
    icon: Shield,
  },
  {
    id: 'terms',
    titleKey: 'terms',
    titleFallback: 'Terms of Service',
    route: ROUTES.TERMS,
    icon: FileText,
  },
  {
    id: 'pricing',
    titleKey: 'pricing',
    titleFallback: 'Pricing',
    route: ROUTES.PRICING,
    icon: Star,
  },
  {
    id: 'support',
    titleKey: 'support',
    titleFallback: 'Contact & Support',
    route: ROUTES.SUPPORT,
    icon: Mail,
  },
  {
    id: 'feedback',
    titleKey: 'feedback',
    titleFallback: 'Send Feedback',
    route: ROUTES.SUPPORT,
    icon: MessageSquare,
  },
];

/** Language options for the accordion */
export const DRAWER_LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
];

/** App version — update via CI/CD */
export const APP_VERSION = '1.0.0' as const;
