export const WALLPAPER_STRINGS = {
  headerTitleHi: "आध्यात्मिक वॉलपेपर",
  headerTitleEn: "Adhyatmic Wallpaper",
  headerSubtitleHi: "अपने मोबाइल को दिव्यता से सजाएँ",
  headerSubtitleEn: "Decorate your mobile with divinity",
  mahabhaktBadgeHi: "महाभक्त",
  mahabhaktBadgeEn: "Mahabhakt",
  toggleStaticHi: "स्थिर (STATIC)",
  toggleStaticEn: "Static",
  toggleLiveHi: "सजीव (LIVE)",
  toggleLiveEn: "Live",
  searchPlaceholderHi: "वॉलपेपर खोजें...",
  searchPlaceholderEn: "Search wallpapers...",
  chooseDeityHi: "देवता चुनें",
  chooseDeityEn: "Choose Deity",
  viewAllHi: "सभी देखें",
  viewAllEn: "View All",
  seeAllHi: "सभी देखें",
  seeAllEn: "See All",
  noWallpapersFoundHi: "कोई वॉलपेपर नहीं मिला।",
  noWallpapersFoundEn: "No wallpapers found.",
  noLiveWallpapersFoundHi: "कोई लाइव वॉलपेपर नहीं मिला।",
  noLiveWallpapersFoundEn: "No live wallpapers found.",
  liveDeityFeedHi: "सजीव देवता दर्शन",
  liveDeityFeedEn: "Live Deity Feed",
  todayLivingDarshanHi: "आज की दिव्य सजीव लीला",
  todayLivingDarshanEn: "Today's Living Darshan",
  liveBadgeHi: "लाइव",
  liveBadgeEn: "Live",
  previewHi: "प्रीव्यू",
  previewEn: "Preview",
  premiumTitleHi: "महाभक्त प्रीमियम",
  premiumTitleEn: "Mahabhakt Premium",
  premiumSubtitle: "108+ Exclusive Wallpapers",
  premiumDetailsHi: "एचडी • विज्ञापन-मुक्त • प्रीमियम",
  premiumDetailsEn: "HD Quality • Ad-Free • Premium",
  exploreHi: "देखें",
  exploreEn: "Explore",
  howToApplyTitleHi: "सजीव वॉलपेपर कैसे लगाएं?",
  howToApplyTitleEn: "How to Apply Live Wallpapers?",
  howToApplyDescHi:
    "सजीव वॉलपेपर डाउनलोड करने पर एचडी मोशन जिफ/वेबपी प्राप्त होगी। किसी भी लाइव वॉलपेपर लॉन्चर की सहायता से इसे अपने लॉकस्क्रीन पर सेट करें।",
  howToApplyDescEn:
    "Downloading a live wallpaper grants you an HD motion webp/gif. Apply it to your lock screen using any live wallpaper settings on Android or iOS.",
  proBadge: "👑 Pro",
  freeBadge: "Free",
};
